/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package perpustakaan;

import com.mysql.jdbc.Connection;
import java.awt.Dimension;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Isepl
 */
public class FBuku extends javax.swing.JFrame {
    Connection con;
    Statement st;
    ResultSet rs;
    /**
     * Creates new form FBuku
     */
    public FBuku() {
        initComponents();
        refreshBuku();
        mainPanel.setPreferredSize(new Dimension(1070, 650));
        this.setLayout(new GridBagLayout());
        this.add(mainPanel, new GridBagConstraints());
        this.setSize(new Dimension(1120, 750));
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.setVisible(true);
    }
    
    private void refreshBuku(){
        try{
            con = Koneksi.getKoneksi();
            String sql1 = "SELECT * FROM buku order by id_buku DESC LIMIT 30";
            st = con.createStatement();
            rs = st.executeQuery(sql1);
            DefaultTableModel model = (DefaultTableModel) tableBuku.getModel();
            model.setRowCount(0);
            while(rs.next()){
                Object[] row = new Object[7];
                row[0] = rs.getString("id_buku");
                row[1] = rs.getString("judul_buku");
                row[2] = rs.getString("pengarang");
                row[3] = rs.getString("penerbit");
                row[4] = rs.getString("tahun");
                row[5] = rs.getString("genre");
                row[6] = rs.getString("stok");
                
                model.addRow(row);
            }
        }catch(SQLException ex){
            JOptionPane.showMessageDialog(null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableBuku = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tambahNomor = new javax.swing.JTextField();
        tambahNama = new javax.swing.JTextField();
        tambahPenerbit = new javax.swing.JTextField();
        tambahPenulis = new javax.swing.JTextField();
        tambahTahun = new javax.swing.JTextField();
        tambahKategori = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        ubahNomor = new javax.swing.JTextField();
        ubahNama = new javax.swing.JTextField();
        ubahPenerbit = new javax.swing.JTextField();
        ubahPenulis = new javax.swing.JTextField();
        ubahTahun = new javax.swing.JTextField();
        ubahKategori = new javax.swing.JTextField();
        ubahStok = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        keywordCari = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("DATA BUKU");
        setMinimumSize(new java.awt.Dimension(1120, 750));
        setPreferredSize(new java.awt.Dimension(1120, 750));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowDeactivated(java.awt.event.WindowEvent evt) {
                formWindowDeactivated(evt);
            }
        });

        mainPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        mainPanel.setMinimumSize(new java.awt.Dimension(1070, 650));
        mainPanel.setPreferredSize(new java.awt.Dimension(1070, 650));
        mainPanel.setRequestFocusEnabled(false);

        tableBuku.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nomor Buku", "Nama", "Penulis", "Penerbit", "Tahun", "Kategori", "Stok"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableBuku.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableBukuMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableBuku);
        if (tableBuku.getColumnModel().getColumnCount() > 0) {
            tableBuku.getColumnModel().getColumn(0).setResizable(false);
            tableBuku.getColumnModel().getColumn(1).setResizable(false);
            tableBuku.getColumnModel().getColumn(2).setResizable(false);
            tableBuku.getColumnModel().getColumn(3).setResizable(false);
            tableBuku.getColumnModel().getColumn(4).setResizable(false);
            tableBuku.getColumnModel().getColumn(5).setResizable(false);
            tableBuku.getColumnModel().getColumn(6).setResizable(false);
        }

        jButton1.setText("Kembali");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Data Buku");

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Tambah Data Buku"));

        jButton3.setText("Tambah data buku");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel1.setText("Nomor Buku");

        jLabel3.setText("Nama");

        jLabel4.setText("Penulis");

        jLabel5.setText("Penerbit");

        jLabel6.setText("Tahun");

        jLabel7.setText("Kategori");

        tambahNomor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahNomorActionPerformed(evt);
            }
        });
        tambahNomor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tambahNomorKeyTyped(evt);
            }
        });

        tambahNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahNamaActionPerformed(evt);
            }
        });

        tambahPenerbit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahPenerbitActionPerformed(evt);
            }
        });

        tambahPenulis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahPenulisActionPerformed(evt);
            }
        });

        tambahTahun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahTahunActionPerformed(evt);
            }
        });
        tambahTahun.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tambahTahunKeyTyped(evt);
            }
        });

        tambahKategori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahKategoriActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGap(27, 27, 27)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tambahNomor)
                    .addComponent(tambahNama)
                    .addComponent(tambahPenulis)
                    .addComponent(tambahPenerbit)
                    .addComponent(tambahTahun)
                    .addComponent(tambahKategori))
                .addContainerGap())
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jButton3)
                .addContainerGap(334, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(tambahNomor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tambahNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tambahPenulis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tambahPenerbit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tambahTahun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(tambahKategori, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(jButton3))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Ubah Data Buku"));

        jButton5.setText("Ubah data buku");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("Hapus data buku");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jLabel8.setText("Nomor Buku");

        jLabel9.setText("Nama");

        jLabel10.setText("Penulis");

        jLabel11.setText("Penerbit");

        jLabel12.setText("Tahun");

        jLabel13.setText("Kategori");

        ubahNomor.setEnabled(false);
        ubahNomor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ubahNomorActionPerformed(evt);
            }
        });

        ubahNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ubahNamaActionPerformed(evt);
            }
        });

        ubahPenerbit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ubahPenerbitActionPerformed(evt);
            }
        });

        ubahPenulis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ubahPenulisActionPerformed(evt);
            }
        });

        ubahTahun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ubahTahunActionPerformed(evt);
            }
        });
        ubahTahun.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ubahTahunKeyTyped(evt);
            }
        });

        ubahKategori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ubahKategoriActionPerformed(evt);
            }
        });

        ubahStok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ubahStokActionPerformed(evt);
            }
        });
        ubahStok.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ubahStokKeyTyped(evt);
            }
        });

        jLabel18.setText("Stok");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jButton5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 225, Short.MAX_VALUE)
                        .addComponent(jButton6)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel13)
                            .addComponent(jLabel12)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(jLabel18))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ubahStok)
                            .addComponent(ubahNomor)
                            .addComponent(ubahNama)
                            .addComponent(ubahPenulis)
                            .addComponent(ubahPenerbit)
                            .addComponent(ubahTahun)
                            .addComponent(ubahKategori))))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(ubahNomor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ubahNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ubahPenulis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ubahPenerbit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ubahTahun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(ubahKategori, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(ubahStok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton5)
                    .addComponent(jButton6)))
        );

        jLabel14.setText("*Klik untuk mengubah");

        keywordCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keywordCariActionPerformed(evt);
            }
        });

        jLabel15.setText("Cari buku");

        jButton4.setText("Cari");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton2.setText("Reset");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 1044, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1))
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(mainPanelLayout.createSequentialGroup()
                                .addComponent(keywordCari, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(28, 28, 28))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel15)
                        .addGap(2, 2, 2)))
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(keywordCari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4)
                    .addComponent(jButton2))
                .addGap(8, 8, 8)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(52, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(52, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 163, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosed

    private void formWindowDeactivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowDeactivated

    // TODO add your handling code here:
    }//GEN-LAST:event_formWindowDeactivated

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        FMenuUtama pustakawan = new FMenuUtama();
        pustakawan.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    // hapus data buku
    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // validasi nomor buku yang akan di hapus
        if (!ubahNomor.getText().equals("")) {
            int result = JOptionPane.showConfirmDialog(null,"Apakah yakin akan menghapus data ini.", "Hapus data buku",
               JOptionPane.YES_NO_OPTION,
               JOptionPane.QUESTION_MESSAGE);
            if(result == JOptionPane.YES_OPTION){
                try{
                    con = Koneksi.getKoneksi();
                    String sql = "DELETE FROM buku WHERE buku.id_buku = '"+ ubahNomor.getText() +"'";
                    st = con.createStatement();
                    st.execute(sql);
                    refreshBuku();
                    JOptionPane.showMessageDialog(null, "Data buku berhasil dihapus");
                    ubahNomor.setText("");
                    ubahNama.setText("");
                    ubahPenulis.setText("");
                    ubahPenerbit.setText("");
                    ubahTahun.setText("");
                    ubahKategori.setText("");
                    ubahStok.setText("");
                    refreshBuku();
                }catch(SQLException e){
                    JOptionPane.showMessageDialog(null, e);
                }
            }
        }else{
            JOptionPane.showMessageDialog(null, "Gagal menghapus data, nomor pilih buku terlebih dahulu");
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void ubahNomorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ubahNomorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ubahNomorActionPerformed

    private void ubahNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ubahNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ubahNamaActionPerformed

    private void ubahPenerbitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ubahPenerbitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ubahPenerbitActionPerformed

    private void ubahPenulisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ubahPenulisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ubahPenulisActionPerformed

    private void ubahTahunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ubahTahunActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ubahTahunActionPerformed

    private void ubahKategoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ubahKategoriActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ubahKategoriActionPerformed

    private void tambahKategoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahKategoriActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tambahKategoriActionPerformed

    private void tambahTahunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahTahunActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tambahTahunActionPerformed

    private void tambahPenulisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahPenulisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tambahPenulisActionPerformed

    private void tambahPenerbitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahPenerbitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tambahPenerbitActionPerformed

    private void tambahNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tambahNamaActionPerformed

    private void tambahNomorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahNomorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tambahNomorActionPerformed

    // tabel buku di klik
    private void tableBukuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableBukuMouseClicked
       int row = tableBuku.rowAtPoint(evt.getPoint());
       ubahNomor.setText(tableBuku.getValueAt(row, 0).toString());
       ubahNama.setText(tableBuku.getValueAt(row, 1).toString());
       ubahPenulis.setText(tableBuku.getValueAt(row, 2).toString());
       ubahPenerbit.setText(tableBuku.getValueAt(row, 3).toString());
       ubahTahun.setText(tableBuku.getValueAt(row, 4).toString());
       ubahKategori.setText(tableBuku.getValueAt(row, 5).toString());
       ubahStok.setText(tableBuku.getValueAt(row, 6).toString());
    }//GEN-LAST:event_tableBukuMouseClicked

    // Tambah buku
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if (tambahNomor.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Gagal menambahkan data, nomor harus di isi");
            tambahNomor.requestFocus();
        }else if(tambahNama.getText().equals("")){
            tambahNama.requestFocus();
            JOptionPane.showMessageDialog(null, "Gagal menambahkan data, nama harus di isi"); 
        }else if(tambahPenulis.getText().equals("")){
            tambahPenulis.requestFocus();
            JOptionPane.showMessageDialog(null, "Gagal menambahkan data, penulis harus di isi"); 
        }else if(tambahPenerbit.getText().equals("")){
            tambahPenerbit.requestFocus();
            JOptionPane.showMessageDialog(null, "Gagal menambahkan data, penerbit harus di isi"); 
        }else if(tambahTahun.getText().equals("")){
            tambahTahun.requestFocus();
            JOptionPane.showMessageDialog(null, "Gagal menambahkan data, tahun harus di isi"); 
        }else if(tambahKategori.getText().equals("")){
            tambahKategori.requestFocus();
            JOptionPane.showMessageDialog(null, "Gagal menambahkan data, kategori harus di isi"); 
        }else{
            try{
                con = Koneksi.getKoneksi();
                String sql = "INSERT INTO buku (id_buku, judul_buku, pengarang, penerbit, tahun, genre, stok) VALUES ('"
                        +tambahNomor.getText()+"', '"
                        +tambahNama.getText()+"', '"
                        +tambahPenulis.getText()+"', '"
                        +tambahPenerbit.getText()+"', '"
                        +tambahTahun.getText()+"', '"
                        +tambahKategori.getText()+"', '"
                        +0+"')";
                
                st = con.createStatement();
                st.execute(sql);
                refreshBuku();
                JOptionPane.showMessageDialog(null, "Data buku berhasil ditambahkan");
                tambahNomor.setText("");
                tambahNama.setText("");
                tambahPenulis.setText("");
                tambahPenerbit.setText("");
                tambahTahun.setText("");
                tambahKategori.setText("");
                tambahNomor.requestFocus();
            }catch(SQLException e){
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    // validasi number
    private void tambahNomorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tambahNomorKeyTyped
        char enter = evt.getKeyChar();
        if(!(Character.isDigit(enter))){
            evt.consume();
        }
    }//GEN-LAST:event_tambahNomorKeyTyped

    // validasi number
    private void tambahTahunKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tambahTahunKeyTyped
        char enter = evt.getKeyChar();
        if(!(Character.isDigit(enter))){
            evt.consume();
        }
    }//GEN-LAST:event_tambahTahunKeyTyped

    // validasi number
    private void ubahTahunKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ubahTahunKeyTyped
        char enter = evt.getKeyChar();
        if(!(Character.isDigit(enter))){
            evt.consume();
        }
    }//GEN-LAST:event_ubahTahunKeyTyped

    private void ubahStokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ubahStokActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ubahStokActionPerformed

    private void ubahStokKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ubahStokKeyTyped
        char enter = evt.getKeyChar();
        if(!(Character.isDigit(enter))){
            evt.consume();
        }
    }//GEN-LAST:event_ubahStokKeyTyped

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        if (ubahNomor.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Gagal mengubah data, silahkan pilih data buku terlebih dahulu");
            ubahNomor.requestFocus();
        }else if(ubahNama.getText().equals("")){
            ubahNama.requestFocus();
            JOptionPane.showMessageDialog(null, "Gagal mengubah data, nama harus di isi"); 
        }else if(ubahPenulis.getText().equals("")){
            ubahPenulis.requestFocus();
            JOptionPane.showMessageDialog(null, "Gagal mengubah data, penulis harus di isi"); 
        }else if(ubahPenerbit.getText().equals("")){
            ubahPenerbit.requestFocus();
            JOptionPane.showMessageDialog(null, "Gagal mengubah data, penerbit harus di isi"); 
        }else if(ubahTahun.getText().equals("")){
            ubahTahun.requestFocus();
            JOptionPane.showMessageDialog(null, "Gagal mengubah data, tahun harus di isi"); 
        }else if(ubahKategori.getText().equals("")){
            ubahKategori.requestFocus();
            JOptionPane.showMessageDialog(null, "Gagal mengubah data, kategori harus di isi"); 
        }else if(ubahStok.getText().equals("")){
            ubahStok.requestFocus();
            JOptionPane.showMessageDialog(null, "Gagal mengubah data, stok harus di isi"); 
        }else{
            try{
                con = Koneksi.getKoneksi();
                String sql = "UPDATE buku SET judul_buku = '"+ ubahNama.getText()
                                +"', pengarang = '"+ ubahPenulis.getText()
                                +"', penerbit = '"+ ubahPenerbit.getText()
                                +"', tahun = '"+ ubahTahun.getText()
                                +"', genre = '"+ ubahKategori.getText()
                                +"', stok = '"+ ubahStok.getText()
                                +"' WHERE buku.id_buku = '"+ ubahNomor.getText()
                                +"'";
                       
                st = con.createStatement();
                st.execute(sql);
                refreshBuku();
                JOptionPane.showMessageDialog(null, "Data buku berhasil diubah");
                ubahNomor.setText("");
                ubahNama.setText("");
                ubahPenulis.setText("");
                ubahPenerbit.setText("");
                ubahTahun.setText("");
                ubahKategori.setText("");
                ubahStok.setText("");
            }catch(SQLException e){
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void keywordCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keywordCariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_keywordCariActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        try{
            con = Koneksi.getKoneksi();
            String sql1 = "SELECT * FROM buku WHERE (judul_buku LIKE '%"
                    +keywordCari.getText()+"%') or (pengarang LIKE '%"
                    +keywordCari.getText()+"%') or (id_buku LIKE '%"
                    +keywordCari.getText()+"%') or (penerbit LIKE '%"
                    +keywordCari.getText()+"%') or (tahun LIKE '%"
                    +keywordCari.getText()+"%') or (genre LIKE '%"
                    +keywordCari.getText()+"%') LIMIT 30";
            st = con.createStatement();
            rs = st.executeQuery(sql1);
            DefaultTableModel model = (DefaultTableModel) tableBuku.getModel();
            model.setRowCount(0);
            while(rs.next()){
                Object[] row = new Object[7];
                row[0] = rs.getString("id_buku");
                row[1] = rs.getString("judul_buku");
                row[2] = rs.getString("pengarang");
                row[3] = rs.getString("penerbit");
                row[4] = rs.getString("tahun");
                row[5] = rs.getString("genre");
                row[6] = rs.getString("stok");
                
                model.addRow(row);
            }
        }catch(SQLException ex){
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        keywordCari.setText("");
        refreshBuku();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FBuku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FBuku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FBuku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FBuku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FBuku().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField keywordCari;
    public javax.swing.JPanel mainPanel;
    private javax.swing.JTable tableBuku;
    private javax.swing.JTextField tambahKategori;
    private javax.swing.JTextField tambahNama;
    private javax.swing.JTextField tambahNomor;
    private javax.swing.JTextField tambahPenerbit;
    private javax.swing.JTextField tambahPenulis;
    private javax.swing.JTextField tambahTahun;
    private javax.swing.JTextField ubahKategori;
    private javax.swing.JTextField ubahNama;
    private javax.swing.JTextField ubahNomor;
    private javax.swing.JTextField ubahPenerbit;
    private javax.swing.JTextField ubahPenulis;
    private javax.swing.JTextField ubahStok;
    private javax.swing.JTextField ubahTahun;
    // End of variables declaration//GEN-END:variables
}
