/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package perpustakaan;

import com.mysql.jdbc.Connection;
import java.awt.Dimension;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.time.LocalDate;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Isepl
 */
public class FPeminjaman extends javax.swing.JFrame {
    Connection con;
    Statement st;
    ResultSet rs;
    
    // temp
    String npmPeminjam = "";
    String tanggalPinjam = "";
    String tenggatKembali = "";
    String[] listPeminjaman = new String[4];
    String[] listPeminjamanStok = new String[4];
    int counterTbl = 0;
    
    
    
    int noBukuSelect = -1;
    /**
     * Creates new form FPeminjaman
     */
    public FPeminjaman() {
        initComponents();
        mainPanel.setPreferredSize(new Dimension(900, 550));
        this.setLayout(new GridBagLayout());
        this.add(mainPanel, new GridBagConstraints());
        this.setSize(new Dimension(940, 640));
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        mainPanel = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        dpTenggatPinjam = new javax.swing.JLabel();
        dpTanggalPinjam = new javax.swing.JLabel();
        dpNama = new javax.swing.JLabel();
        dpNPM = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        bukuPinjam = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        pilihanBuku = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableBuku = new javax.swing.JTable();
        keywordCariBuku = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableMahasiswa = new javax.swing.JTable();
        keywordCariMahasiswa = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jLabel17.setText("jLabel17");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("FORM PEMINJAMAN BUKU");
        setMinimumSize(new java.awt.Dimension(940, 640));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        mainPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        mainPanel.setMinimumSize(new java.awt.Dimension(880, 550));
        mainPanel.setPreferredSize(new java.awt.Dimension(858, 540));
        mainPanel.setRequestFocusEnabled(false);

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Data Peminjam"));

        jLabel11.setText("NPM");

        jLabel12.setText("Nama");

        jLabel13.setText("Tanggal Pinjam");

        jLabel14.setText("Tenggat Pinjam");

        dpTenggatPinjam.setText(":");

        dpTanggalPinjam.setText(":");

        dpNama.setText(":");

        dpNPM.setText(":");

        jButton7.setText("Reset");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(jLabel13)
                    .addComponent(jLabel12)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dpNPM)
                    .addComponent(dpNama)
                    .addComponent(dpTanggalPinjam)
                    .addComponent(dpTenggatPinjam))
                .addGap(0, 283, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton7))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(dpNPM))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(dpNama))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(dpTanggalPinjam))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(dpTenggatPinjam))
                .addGap(18, 18, 18)
                .addComponent(jButton7))
        );

        jButton1.setText("Kembali");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Form Peminjaman Buku");

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Daftar buku yang akan dipinjam"));
        jPanel4.setToolTipText("");

        bukuPinjam.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nomor Buku", "Nama Buku", "Stok"
            }
        ));
        bukuPinjam.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bukuPinjamMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(bukuPinjam);
        if (bukuPinjam.getColumnModel().getColumnCount() > 0) {
            bukuPinjam.getColumnModel().getColumn(0).setMinWidth(100);
            bukuPinjam.getColumnModel().getColumn(0).setMaxWidth(100);
            bukuPinjam.getColumnModel().getColumn(2).setMaxWidth(50);
        }

        jLabel7.setText("*Untuk menghapus klik terlebih dahulu dan tombolnya dibawah");

        jLabel8.setText("Pilihan: ");

        jButton6.setText("Hapus");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jLabel10.setText("*Batas peminjaman buku maksimal 3");

        pilihanBuku.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 385, Short.MAX_VALUE)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pilihanBuku)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton6))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel10)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(pilihanBuku)))
                    .addComponent(jButton6, javax.swing.GroupLayout.Alignment.TRAILING)))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Cari Buku"));

        tableBuku.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nomor Buku", "Nama", "Stok"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableBuku.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableBukuMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableBuku);
        if (tableBuku.getColumnModel().getColumnCount() > 0) {
            tableBuku.getColumnModel().getColumn(0).setMinWidth(100);
            tableBuku.getColumnModel().getColumn(0).setMaxWidth(100);
        }

        keywordCariBuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keywordCariBukuActionPerformed(evt);
            }
        });

        jButton4.setText("Cari");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton2.setText("Reset");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel6.setText("*Klik untuk memilih");

        jLabel9.setText("*Stok yang kosong tidak akan muncul");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 416, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(keywordCariBuku)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel9))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(keywordCariBuku, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addComponent(jLabel9))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Cari Mahasiswa"));

        tableMahasiswa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NPM", "Nama", "Tanggal Bergabung"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableMahasiswa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMahasiswaMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tableMahasiswa);
        if (tableMahasiswa.getColumnModel().getColumnCount() > 0) {
            tableMahasiswa.getColumnModel().getColumn(0).setMinWidth(90);
            tableMahasiswa.getColumnModel().getColumn(0).setMaxWidth(170);
        }

        keywordCariMahasiswa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keywordCariMahasiswaActionPerformed(evt);
            }
        });

        jButton5.setText("Reset");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton3.setText("Cari");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel5.setText("*Klik untuk memilih");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(keywordCariMahasiswa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 416, Short.MAX_VALUE)
            .addComponent(jLabel5)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(keywordCariMahasiswa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5)
                    .addComponent(jButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5))
        );

        jButton8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton8.setText("SIMPAN PEMINJAMAN");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(434, 434, 434)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(694, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        FMenuUtama pustakawan = new FMenuUtama();
        pustakawan.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tableBukuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableBukuMouseClicked
        boolean cek = true;
        int count= bukuPinjam.getModel().getRowCount();
        if (count <= 2){
            int row = tableBuku.rowAtPoint(evt.getPoint());     
            DefaultTableModel model = (DefaultTableModel) bukuPinjam.getModel();
            Object[] rows = new Object[3];
            rows[0] = tableBuku.getValueAt(row, 0).toString();
            rows[1] = tableBuku.getValueAt(row, 1).toString();
            rows[2] = tableBuku.getValueAt(row, 2).toString();
            if(count > 0){
                for(int i = 0; i<count; i++){
                    if(rows[0].equals(bukuPinjam.getValueAt(i, 0).toString())){
                        cek = false;
                    }
                }   
            }
            if(cek){
                model.addRow(rows);
            } else{
                JOptionPane.showMessageDialog(null, "Buku sudah ada");
            }
        }else{
            JOptionPane.showMessageDialog(null, "Peminjaman buku maksimal 3");
        }
    }//GEN-LAST:event_tableBukuMouseClicked

    private void keywordCariBukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keywordCariBukuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_keywordCariBukuActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        try{
            con = Koneksi.getKoneksi();
            String sql1 = "SELECT * FROM buku WHERE ((judul_buku LIKE '%"
            +keywordCariBuku.getText()+"%') or (pengarang LIKE '%"
            +keywordCariBuku.getText()+"%') or (penerbit LIKE '%"
            +keywordCariBuku.getText()+"%') or (tahun LIKE '%"
            +keywordCariBuku.getText()+"%') or (genre LIKE '%"
            +keywordCariBuku.getText()+"%')) and (stok > 0)  LIMIT 10";
            st = con.createStatement();
            rs = st.executeQuery(sql1);
            DefaultTableModel model = (DefaultTableModel) tableBuku.getModel();
            model.setRowCount(0);
            while(rs.next()){
                Object[] row = new Object[7];
                row[0] = rs.getString("id_buku");
                row[1] = rs.getString("judul_buku");
                row[2] = rs.getString("stok");

                model.addRow(row);
            }
        }catch(SQLException ex){
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        resetDataBuku();
    }//GEN-LAST:event_jButton2ActionPerformed
    private void resetDataBuku(){
        keywordCariBuku.setText("");
        DefaultTableModel model = (DefaultTableModel) tableBuku.getModel();
        model.setRowCount(0);
    }
    
    private void tableMahasiswaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMahasiswaMouseClicked
        int row = tableMahasiswa.rowAtPoint(evt.getPoint());
        LocalDate now = LocalDate.now();
        String pinjam = now.toString();
        String tenggat = now.plusDays(14).toString();
       
        dpNPM.setText(": "+tableMahasiswa.getValueAt(row,0).toString());
        dpNama.setText(": "+tableMahasiswa.getValueAt(row,1).toString());
        dpTanggalPinjam.setText(": "+pinjam);
        dpTenggatPinjam.setText(": "+tenggat);


        npmPeminjam = tableMahasiswa.getValueAt(row,0).toString();
        tanggalPinjam = pinjam;
        tenggatKembali = tenggat;
    }//GEN-LAST:event_tableMahasiswaMouseClicked

    private void keywordCariMahasiswaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keywordCariMahasiswaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_keywordCariMahasiswaActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try{
            con = Koneksi.getKoneksi();
            String sql1 = "SELECT * FROM mahasiswa WHERE (nama LIKE '%"+keywordCariMahasiswa.getText()+"%') or (npm LIKE '%"+keywordCariMahasiswa.getText()+"%') LIMIT 10";
            st = con.createStatement();
            rs = st.executeQuery(sql1);
            DefaultTableModel model = (DefaultTableModel) tableMahasiswa.getModel();
            model.setRowCount(0);
            while(rs.next()){
                Object[] row = new Object[13];
                row[0] = rs.getString("npm");
                row[1] = rs.getString("nama");
                row[2] = rs.getString("tanggal_bergabung");
                model.addRow(row);
            }
        }catch(SQLException ex){
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        resetTableMahasiswa();
    }//GEN-LAST:event_jButton5ActionPerformed
    private void resetTableMahasiswa(){
        keywordCariMahasiswa.setText("");
        DefaultTableModel model = (DefaultTableModel) tableMahasiswa.getModel();
        model.setRowCount(0);
    }
    
    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        if(noBukuSelect >= 0){
            resetDataPinjamBuku();
        }else{
            JOptionPane.showMessageDialog(null, "Data yang akan dihapus harus dipilih terlebih dahulu.");
        }
    }//GEN-LAST:event_jButton6ActionPerformed
    
    private void resetDataPinjamBuku(){
        DefaultTableModel model = (DefaultTableModel) bukuPinjam.getModel();
        model.removeRow(noBukuSelect);
        pilihanBuku.setText("");
        noBukuSelect = -1;
    }
    
    private void bukuPinjamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bukuPinjamMouseClicked
        int row = bukuPinjam.rowAtPoint(evt.getPoint());
        pilihanBuku.setText(bukuPinjam.getValueAt(row,1).toString());
        noBukuSelect = row;
    }//GEN-LAST:event_bukuPinjamMouseClicked

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // cek peminjam
        if (!npmPeminjam.equals("")) {
            // cek buku yang dipinjam
            int count= bukuPinjam.getModel().getRowCount();
            if(count > 0){
                try{
                    con = Koneksi.getKoneksi();
                    String sql = "INSERT INTO peminjaman (id, npm, status) VALUES (NULL, '"+npmPeminjam+"', 'Dipinjam')";
                    
                    st = con.createStatement();
                    st.executeUpdate(sql, Statement.RETURN_GENERATED_KEYS);
                    int autoIncKeyFromApi = -1;
                    rs = st.getGeneratedKeys();

                    if (rs.next()) {
                        autoIncKeyFromApi = rs.getInt(1);
                        String pre = "INSERT INTO peminjaman_detail (id, id_peminjaman, npm, id_buku, tanggal_pinjam, tenggat_pinjam, tanggal_kembali, status, denda) VALUES ";
                        String insert = "";
                        counterTbl = count;
                        for (int i = 0; i < count; i++) {
                            insert += insert.equals("") ? "" : ", ";
                            insert += "(NULL, '"+autoIncKeyFromApi+"', '"+npmPeminjam+"', '"+bukuPinjam.getValueAt(i,0).toString()+"', '"+tanggalPinjam+"', '"+tenggatKembali+"', NULL, 'Dipinjam', '0')";
                            listPeminjaman[i] = bukuPinjam.getValueAt(i,0).toString();
                            listPeminjamanStok[i] = bukuPinjam.getValueAt(i,2).toString();
                        }
                              
                        try{
                            con = Koneksi.getKoneksi();
                            st = con.createStatement();
                            st.execute(pre+insert);
                            JOptionPane.showMessageDialog(null, "Data peminjaman berhasil ditambahkan");

                            // reset semua data
                            resetTableMahasiswa();
                            resetDataBuku();
                            resetDataPeminjam();
                            // hapus tabel buku pinjam
                            pilihanBuku.setText("");
                            noBukuSelect = -1;
                            DefaultTableModel model = (DefaultTableModel) bukuPinjam.getModel();
                            model.setRowCount(0);
                        }catch(SQLException e){
                            JOptionPane.showMessageDialog(null, e);
                        }
                    } else {

                        // throw an exception from here
                    }

//                    System.out.println("Key returned from getGeneratedKeys():" + autoIncKeyFromApi);
                } catch (SQLException ex) {
                    Logger.getLogger(FPeminjaman.class.getName()).log(Level.SEVERE, null, ex);
                }finally{
                    for (int i = 0; i < counterTbl; i++) {
                        kurangiStokExe(listPeminjamanStok[i],listPeminjaman[i]);
                    }
                }
            }else{
                JOptionPane.showMessageDialog(null, "Buku belum dipilih");
            }
        }else{
            JOptionPane.showMessageDialog(null, "Peminjam belum dipilih");
        }
        
    }//GEN-LAST:event_jButton8ActionPerformed


    private void kurangiStokExe(String stok, String nomor){
        try{
            int stok1 = Integer.parseInt(stok);
            String sql1 = "UPDATE buku SET stok = '"+ --stok1 +"' WHERE id_buku = '"+nomor+"'";
            con = Koneksi.getKoneksi();
            st = con.createStatement();
            st.execute(sql1);
        }catch(SQLException ex){
            JOptionPane.showMessageDialog(null, ex);
        }
    }    
    
    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        resetDataPeminjam();
    }//GEN-LAST:event_jButton7ActionPerformed
    
    private void resetDataPeminjam(){
        npmPeminjam = "";
        tanggalPinjam = "";
        tenggatKembali = "";
        
        dpNPM.setText(":");
        dpNama.setText(":");
        dpTanggalPinjam.setText(":");
        dpTenggatPinjam.setText(":");
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FPeminjaman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FPeminjaman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FPeminjaman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FPeminjaman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FPeminjaman().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable bukuPinjam;
    private javax.swing.JLabel dpNPM;
    private javax.swing.JLabel dpNama;
    private javax.swing.JLabel dpTanggalPinjam;
    private javax.swing.JLabel dpTenggatPinjam;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField keywordCariBuku;
    private javax.swing.JTextField keywordCariMahasiswa;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JLabel pilihanBuku;
    private javax.swing.JTable tableBuku;
    private javax.swing.JTable tableMahasiswa;
    // End of variables declaration//GEN-END:variables
}
